#!/usr/bin/env python
# -*- coding: utf-8 -*-
import sys
from math import radians, cos, sin, asin, sqrt

def haversine(lon1, lat1, lon2, lat2):
    """
    Calculate the great circle distance between two points
    on the earth (specified in decimal degrees)
    """
    # convert decimal degrees to radians
    lon1, lat1, lon2, lat2 = map(radians, [lon1, lat1, lon2, lat2])

    # haversine formula
    dlon = lon2 - lon1
    dlat = lat2 - lat1
    a = sin(dlat / 2) ** 2 + cos(lat1) * cos(lat2) * sin(dlon / 2) ** 2
    c = 2 * asin(sqrt(a))
    r = 6371  # Radius of earth in kilometers. Use 3956 for miles
    return c * r
    
if __name__ == "__main__":
	#print(len(sys.argv))
	#print(str(sys.argv))
	if len(sys.argv) > 1:
		lat1, lon1 = float(sys.argv[2]), float(sys.argv[3])
		lat2, lon2 = float(sys.argv[4]), float(sys.argv[5])
		
		distance = haversine(lon1, lat1, lon2, lat2)
		print(distance)
	'''
	else:
    	# Le Wagon location
    	lat1, lon1 = 48.865070, 2.380009
    	#Insert your coordinates from google maps here
    	lat2, lon2 = 52.34, 35.67
    	distance = haversine(lon1, lat1, lon2, lat2)
    	print(distance)
    '''